<a href="https://colab.research.google.com/github/weepingwillow2001/data_analysis_practice/blob/main/5%EC%9E%A5/5_2_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

# 두 Series 생성
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4.0, 3.1], index=["a", "c", "e", "f", "g"])

# 두 Series 더하기
result = s1 + s2
print(result)

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64


In [3]:
# 두 개의 서로 다른 DataFrame 생성
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                 index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                 index=["Utah", "Ohio", "Texas", "Oregon"])

# df1 출력
print(df1)

# df2 출력
print(df2)

# 두 DataFrame을 더하면 겹치는 인덱스와 컬럼만 연산 수행, 나머지는 NaN
print(df1 + df2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN


In [4]:
# 하나의 열만 가진 두 개의 DataFrame 생성
# 공통 열이 전혀 없는 경우
df1 = pd.DataFrame({"A": [1, 2]})    # 딕셔너리 형태도 가능!
df2 = pd.DataFrame({"B": [3, 4]})

# df1 출력
print(df1)

# df2 출력
print(df2)

# 두 DataFrame 더하기
print(df1 + df2)

# 겹치는 열이 없기 때문에 모든 값이 NaN(Not a Number)으로 채워짐

   A
0  1
1  2
   B
0  3
1  4
    A   B
0 NaN NaN
1 NaN NaN


In [6]:
# 두 개의 DataFrame 생성
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list("abcde"))

# df2의 'b' 열에 NaN 값 할당(np.nan)
df2.loc[1, 'b'] = np.nan

# df1 출력
print(df1)

# df2 출력
print(df2)

# 두 DataFrame 더하기 (NaN + 값 = NaN!!!)
print(df1 + df2)

# add 메서드와 fill_value 사용하여 NaN 값 처리
print(df1.add(df2, fill_value=0))
#       a     b     c     d     e
# 0   0.0   2.0   4.0   6.0   4.0
# 1   9.0   5.0  13.0  15.0   9.0
# 2  18.0  20.0  22.0  24.0  14.0
# 3  15.0  16.0  17.0  18.0  19.0

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [7]:
# 모든 요소에 대해 1을 나누는 연산
print(1 / df1)

# rdiv 메서드로 동일한 작업 수행 (r은 'reverse'의 의미)
print(df1.rdiv(1))

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909
       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909


In [8]:
# df2의 열을 기준으로 df1을 재색인하고 누락된 열(e)은 0으로 채움

print(df1.reindex(columns=df2.columns, fill_value=0))

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0


In [9]:
# 브로드캐스팅 - 넘파이
# 2차원 배열에서 1차원 배열을 빼면, 1차원 배열이 각 행에 대해 브로드캐스팅됨

arr = np.arange(12.).reshape((3, 4))
print(arr)

print(arr[0])

print(arr - arr[0])   # 각 행 숫자에서 0행의 숫자 빼기
# array([[0., 0., 0., 0.],
#        [4., 4., 4., 4.],
#        [8., 8., 8., 8.]])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[0. 1. 2. 3.]
[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [10]:
#브로드캐스팅 - 판다스

frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list("bde"),
                    index=["Utah", "Ohio", "Texas", "Oregon"])
print(frame)

series = frame.iloc[0]
print(series)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64


In [11]:
# Series의 색인을 DataFrame의 열에 맞추고 나서 행으로 브로드캐스팅함
# 넘파이 경우와 같은 원리로 작동!

print(frame - series)
#         b    d    e
# Utah    0.0  0.0  0.0
# Ohio    3.0  3.0  3.0
# Texas   6.0  6.0  6.0
# Oregon  9.0  9.0  9.0

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0


In [12]:
# Series의 색인이 DataFrame의 열과 "다른" 경우

series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
print(series2)

print(frame + series2)
#         b     d     e     f
# Utah    0.0   NaN   3.0   NaN
# Ohio    3.0   NaN   6.0   NaN
# Texas   6.0   NaN   9.0   NaN
# Oregon  9.0   NaN  12.0   NaN

# 공통 열('b', 'e')에 대해서만 연산 수행
# DataFrame에만 있는 'd' 열은 모두 NaN (값 + NaN = NaN !!)
# Series2에만 있는 'f' 열은 결과에 포함되지만 값은 모두 NaN (NaN + 값 = NaN !!)

b    0
e    1
f    2
dtype: int64
          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN


In [ ]:
# "행"을 기준으로 연산을 수행하고 싶을 때: axis="index" 이용

series3 = frame["d"]
print(series3)
# Utah      1.0
# Ohio      4.0
# Texas     7.0
# Oregon   10.0
# Name: d, dtype: float64

print(frame.sub(series3, axis="index"))
#         b    d    e
# Utah   -1.0  0.0  1.0
# Ohio   -1.0  0.0  1.0
# Texas  -1.0  0.0  1.0
# Oregon -1.0  0.0  1.0